config/routes.rb
Rails.application.routes.draw do
 root to: 'pages#home'
 get 'about', to: 'pages#about'
 get 'services', to: 'pages#services'
 get 'pricing', to: 'pages#pricing'
 get 'contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
  
  def services
  end
  
  def pricing
  end
  
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Furiends Furever</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="/" class="navbar-brand">
            <%= image_tag("Furiends Forever Logo", class: "logo") %>
          </a>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Services", services_path %></li>
            <li><%= link_to "Pricing", pricing_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    
    <%= yield %>
      
  </body>
</html>

app/views/pages/about.html.erb
<div class="container text-center">
<h1>About Page</h1>
    <p>We are the Furiends Furever team. Our business focuses on providing a
    family's love and attention when your fur babies can't be with you!</p>
</div>

app/views/pages/contact.html.erb
<h1>Contact Page</h1>

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid">
    <h1><i class="fa fa-heart"></i> Welcome to Furiends Forever Pet Services <i 
    class="fa fa-heart"></i></h1>
    <h3>Loving, Professional, and Affordable Dog Walking and Pet Sitting</h3>
</div>
<div class="home-body">
    <div class="container pic-text-container1 text-center">
        <p>Furiends Forever pet services is a dog walking and pet sitting business 
        that focuses on keeping your fur babies happy when you can't be home to do 
        it yourself. We pride ourselves on our raw love for animals and giving them 
        the exercise, training, attention, and affection that they need.</p>
        <div class="row">
            <div class="col-md-4 pic-text1">
                <%= image_tag("cassi16", class: "picture1") %>
            </div>
            <div class="col-md-4 pic-text2">
                <%= image_tag("cassi14", class: "picture2") %>
            </div>
            <div class="col-md-4 pic-text3">
                <%= image_tag("cassi11", class: "picture3") %>
            </div>
        </div>
    </div>
    <div class="container pic-text-container2">
        <div class="row">
            <p>None of us can be with our pets as much as we'd like, so we're here to
            fill in the gap!</p>
            <div class="col-xs-6 pic-text4">
                <p>Rain, snow, sleet, and other weather conditions will not stop 
                your pup's walk.</p>
                <%= image_tag("cassi2", class: "picture4") %>
            </div>
            <div class="col-xs-6 pic-text5">
                <%= image_tag("cassi13", class: "picture5") %>
                <p>Birds, rabbits, ferrets, hamsters, and all other fur babies 
                are accommodated.</p>
            </div>
        </div>
    </div>
    <div class="container pic-text-container3">
        <div class="row">
            <div class="col-xs-6 pic-text6">
                <p>Text messages and pictures (Pupdates) are sent during every 
                interaction with your pet!</p>
                <%= image_tag("pupdate2.PNG", class: "picture6 img-fluid max-width: 100%") %>
            </div>
            <div class="col-xs-6 pic-text6">
                <%= image_tag("pupdate1.PNG", class: "picture7") %>
                <p>We'll tell you how they did on their visit and if they caused any trouble
                while you've been gone.</p>
            </div>
        </div>
    </div>
</div>

app/views/pages/pricing.html.erb
<h1>Pricing Page</h1>

app/views/pages/services.html.erb
<h1>Services Page</h1>